server:
  port: 8082
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/swarmbuy?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  mapper-locations: classpath:**/dao/*/*.xml*
